additional_commands:
  foo:
    flags:
    - BAR
    - BAZ
    kwargs:
      HEADERS: '*'
      SOURCES: '*'
      DEPENDS: '*'
bullet_char: '*'
dangle_parens: false
keyword_case: upper
command_case: lower
enum_char: .
line_ending: unix
line_width: 120
max_branches: 20
max_arguments: 6
max_statements: 60
max_pargs_hwrap: 3
separate_ctrl_name_with_space: false
separate_fn_name_with_space: false
tab_size: 4

markup:
  enable_markup: false
